[package]
name = "docfind"
version = "0.2.0"
edition = "2024"

[dependencies]
docfind_core = { path = "../core", features = ["cli"] }
serde_json = "1.0.145"
wasm-encoder = { version = "0.240.0", features = ["wasmparser"] }
wasmparser = "0.240.0"
