[package]
name = "docfind-wasm"
version = "0.2.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
docfind_core = { path = "../core", features = ["wasm"] }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
